### ISSUE TITLE
What is nspassword in the json?

### ISSUE THREAD

**Issue by AlgosoftTech** [di/slack-irc-heroku-bridge#1]
I tried deploying it a several times but somehow unable to make it work, can you help?

**Comment by AlgosoftTech** [comment]
Proper error is as below:
Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch

**Comment by AlgosoftTech** [comment]
and there is also a warning:
SlackDataStore is deprecated and will be removed in the next major version. See project documentation for a migration guide

**Comment by di** [comment]
> What is nspassword in the json?

`nsPassword` should be the same value as `password`

> Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch

You should be running a worker process, not a web process. See step #10 in the readme.

**Comment by AlgosoftTech** [comment]
Thanks, worked beautifully.
SlackDataStore still gives a warning.

**Comment by AlgosoftTech** [comment]
How do we circumvent the 249 character limit of slack what I do?

**Comment by di** [comment]
> SlackDataStore still gives a warning.

This can be ignored

> How do we circumvent the 249 character limit of slack what I do?

There's no way to do this unfortunately

**Comment by AlgosoftTech** [comment]
Thanks, for being super helpful... 👍

**Comment by di** [comment]
No worries! Hope this works for you. Feel free to close the issue if this has resolved your questions.

**Comment by AlgosoftTech** [comment]
Yes, it did work.
